---

- name: Ensure PHP CLI is configured via php.ini
  become: yes
  template:
    src: "templates/{{ php_version }}/cli-php.ini.j2"
    dest: "/etc/php/{{ php_version }}/cli/php.ini"
    mode: 0644
