---

- name: Download ionCube source
  unarchive:
    dest: /opt/
    src: "https://s3.amazonaws.com/downloads3.ioncube.com/loader_downloads/ioncube_loaders_lin_x86-64_{{ php_ioncube_version }}.tar.gz"
    remote_src: yes
  when: php_ioncube_enable

- name: Link ionCube PHP extension
  file:
    src: "/opt/ioncube/ioncube_loader_lin_{{ php_version }}.so"
    # TODO: Figure out how to use PHP's extension dir setting instead of hardcoded path
    dest: "/usr/lib/php/20131226/ioncube_loader_lin_{{ php_version }}.so"
    state: link

- name: PHP conf file for ionCube
  copy:
    content: |
      ; {{ ansible_managed }}
      ;
      ; configuration for ionCube module
      ; priority=00
      zend_extension=ioncube_loader_lin_{{ php_version }}.so
    dest: "/etc/php/{{ php_version }}/mods-available/ioncube.ini"

- name: "Manage ionCube PHP extension: {{ 'enabled' if php_ioncube_enable else 'disabled' }}"
  command: "{{ 'phpenmod' if php_ioncube_enable else 'phpdismod' }} -v {{ php_version }} ioncube"
  notify: restart php-fpm
