---

- name: Fail if php version is not supported
  fail:
    msg: "PHP {{ php_version }} is not in the supported_php_versions list"
  when: php_version not in supported_php_versions
  tags:
    - php

- name: Add PHP-PPA
  become: yes
  apt_repository:
    repo: "ppa:ondrej/php"
    update_cache: yes
  tags:
    - php

- name: Install PHP version
  become: yes
  apt:
    name: "php{{ php_version }}"
    force_apt_get: yes
  tags:
    - php

- name: Ensure PHP is set to use {{ php_version }}
  become: yes
  alternatives:
    name: php
    path: "/usr/bin/php{{ php_version }}"
  tags:
    - php

- name: Build PHP package list
  set_fact:
    php_packages: "{{ php_extensions | map('regex_replace', '^(.*)', 'php' ~ php_version ~ '-\\1') | list }}"
  tags:
    - php

- name: Install PHP packages
  become: yes
  apt:
    name: "{{ php_packages }}"
    state: latest
    force_apt_get: yes
  tags:
    - php

- import_tasks: cli.yml
  tags:
    - php
    - php-cli

- import_tasks: xdebug.yml
  when: php_xdebug_install
  tags:
    - php
    - php-xdebug

- import_tasks: fpm.yml
  when: php_fpm_install
  tags:
    - php
    - php-fpm

- import_tasks: cleanup.yml
  tags:
    - php
