---

- name: Add PHP-PPA
  apt_repository:
    repo: "ppa:ondrej/php"
    update_cache: yes
  tags:
    - php

- name: Install PHP packages
  become: yes
  apt:
    name: "php{{ php_version }}-{{ item }}"
    state: present
  with_items: "{{ php_extensions }}"
  tags:
    - php

- name: Ensure PHP is set to use {{ php_version }}
  become: yes
  alternatives:
    name: php
    path: "/usr/bin/{{ php_version }}"
  tags:
    - php

- include: fpm.yml
  when: php_fpm_enable