---

- name: Check if php version is supported
  fail:
    msg: "PHP {{ php_version }} is not in the supported_php_versions list"
  when: php_version not in supported_php_versions
  tags:
    - php

- name: Add PHP-PPA
  become: yes
  apt_repository:
    repo: "ppa:ondrej/php"
    update_cache: yes
  tags:
    - php

- name: Install PHP version
  become: yes
  apt:
    name: "php{{ php_version }}"
  tags:
    - php

- name: Install PHP packages
  become: yes
  apt:
    name: "php{{ php_version }}-{{ item }}"
    state: present
  with_items: "{{ php_extensions }}"
  tags:
    - php

- import_tasks: cli.yml
  tags:
    - php
    - php-cli

- import_tasks: fpm.yml
  when: php_fpm_install
  tags:
    - php
    - php-fpm
