---

- name: "NewRelic APT key: {{ 'present' if php_newrelic_enable else 'absent' }}"
  apt_key:
    id: 548C16BF
    url: https://download.newrelic.com/548C16BF.gpg
    state: "{{ 'present' if php_newrelic_enable else 'absent' }}"


- name: "NewRelic APT repository: {{ 'present' if php_newrelic_enable else 'absent' }}"
  apt_repository:
    repo: "deb http://apt.newrelic.com/debian/ newrelic non-free"
    update_cache: yes
    state: "{{ 'present' if php_newrelic_enable else 'absent' }}"

- name: Preconfigure NewRelic
  debconf:
    name: newrelic-php5
    question: "newrelic-php5/{{ item.setting }}"
    value: "{{ item.value }}"
    vtype: string
  with_items:
    - { setting: 'license-key', value: "{{ php_newrelic_license_key }}" }
    - { setting: 'application-name', value: "{{ php_newrelic_application_name }}" }
  when: php_newrelic_enable

- name: "NewRelic package: {{ 'present' if php_newrelic_enable else 'absent' }}"
  apt:
    name: newrelic-php5
    state: "{{ 'present' if php_newrelic_enable else 'absent' }}"

